# ![DeepLearning-with-Pytorch](https://puchan-hci.github.io/myweb/DeepLearning-with-Pytorch/img/01_1.jpg)Deep Learning with PyTorch


# It starts with a tensor
 The process begins by converting our input into floating-point numbers.  Since floating-point numbers are the way a network deals with information, we need a
way to encode real-world data of the kind we want to process into something digestible
by a network and then decode the output back to something we can understand and
use for our purpose.
![Floating point](https://puchan-hci.github.io/myweb/DeepLearning-with-Pytorch/img/01_2.jpg)

In the context of deep learning, tensors refer to the generalization of vectors and matrices to an arbitrary number of dimensions. Another name for the same concept is multidimensional array. The dimensionality of a tensor coincides with the
number of indexes used to refer to scalar values within the tensor.
![Tensors](https://puchan-hci.github.io/myweb/DeepLearning-with-Pytorch/img/01_3.jpg)

# Constructing our first tensors
Let’s construct our first PyTorch tensor and see what it looks like.

In [6]:
import torch                # Imports the torch module
a = torch.ones(3)       # Creates a one-dimensional tensor of size 3 filled with 1s

# After importing the torch module, we call a function that creates a (one-dimensional)
# tensor of size 3 filled with the value 1.0. We can access an element using its zero-based
# index or assign a new value to it.

print(a)
print(a[1])
print(float(a[1]))

# Assign a new value
a[2] = 2.0
print(a)
print(float(a[2]))

tensor([1., 1., 1.])
tensor(1.)
1.0
tensor([1., 1., 2.])
2.0


Python lists or tuples of numbers are collections of Python objects that are individually allocated in memory.

![Tensors](https://puchan-hci.github.io/myweb/DeepLearning-with-Pytorch/img/01_4.jpg)

In [17]:
points = torch.zeros(6)   # Using .zeros is just a way to get an appropriately sized array.
points[0] = 4.0                    # We overwrite those zeros with the values we actually want.
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

# We can also pass a Python list to the constructor, to the same effect:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
print(points)

# To get the coordinates of the first point, we do the following:
print(float(points[0]), float(points[1]))

# It would be practical to have the first index refer to individual 2D points
# rather than point coordinates. For this, we can use a 2D tensor:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)

# Here, we pass a list of lists to the constructor. We can ask the tensor about its shape:
print(points.shape)

# This informs us about the size of the tensor along each dimension.
# We could also use zeros or ones to initialize the tensor, providing the size as a tuple:
points = torch.zeros(3, 2)
print(points)

# Now we can access an individual element in the tensor using two indices:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)
print(points[0, 0])
print(points[0, 1])
print(points[1, 0])
print(points[1, 1])
print(points[2, 0])
print(points[2, 1])

# We can also access the first element in the tensor to get the 2D coordinates
# of the first point:
print(points[0])

tensor([4., 1., 5., 3., 2., 1.])
4.0 1.0
tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
torch.Size([3, 2])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor(4.)
tensor(1.)
tensor(5.)
tensor(3.)
tensor(2.)
tensor(1.)
tensor([4., 1.])


# Managing a tensor’s dtype attribute
In order to allocate a tensor of the right numeric type, we can specify the proper
dtype as an argument to the constructor. For example:

In [24]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

# We can find out about the dtype for a tensor by accessing the corresponding attribute:
print(short_points.dtype)
print(double_points.dtype)

# We can also cast the output of a tensor creation function to the right type
# using the corresponding casting method, such as
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
print(short_points.dtype)
print(double_points.dtype)

# or the more convenient to method:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)
print(short_points.dtype)
print(double_points.dtype)

# When mixing input types in operations, the inputs are converted to the larger type
# automatically. Thus, if we want 32-bit computation, we need to make sure all our
# inputs are (at most) 32-bit:
points_64 = torch.rand(5, dtype=torch.double)  # rand initializes the tensor elements to random numbers between 0 and 1.
points_short = points_64.to(torch.short)
print(points_64 * points_short)


torch.int16
torch.float64
torch.int16
torch.float64
torch.int16
torch.float64
tensor([0., 0., 0., 0., 0.], dtype=torch.float64)


# Tensors: Scenic views of storage
Values in tensors are allocated in contiguous chunks of memory managed by *torch.Storage* instances.

![Tensors](https://puchan-hci.github.io/myweb/DeepLearning-with-Pytorch/img/01_5.jpg)

In [29]:
# Reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points.storage())

# We can also index into a storage manually. For instance:
points_storage = points.storage()
print(points_storage[0])
print(points_storage[1])
print(points_storage[2])

# We can’t index a storage of a 2D tensor using two indices. The layout of
# a storage is always one-dimensional, regardless of the dimensionality of
# any and all tensors that might refer to it. At this point, it shouldn’t come as
#  a surprise that changing the value of a storage leads to changing the content of
#  its referring tensor:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
print(points)


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
4.0
1.0
5.0
tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])


# Modifying stored values
In-place operations
In addition to the operations on tensors introduced in the previous section, a small
number of operations exist only as methods of the Tensor object. They are recognizable from a trailing underscore in their name, like zero_, which indicates that the
method operates in place by modifying the input instead of creating a new output tensor and returning it. For instance, the zero_ method zeros out all the elements of the input.

In [30]:
a = torch.ones(3, 2)
print(a)
a.zero_()
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


# NumPy interoperability
PyTorch tensors can
be converted to NumPy arrays and vice versa very efficiently. By doing so, we can take
advantage of the huge swath of functionality in the wider Python ecosystem that has
built up around the NumPy array type.

In [6]:
# Get a NumPy array out of tensor
points = torch.ones(3, 4)
points_np = points.numpy()
print(points_np)

# Obtain a PyTorch tensor from a NumPy array
points = torch.from_numpy(points_np)
print(points)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


# Serializing tensors
Creating a tensor on the fly is all well and good, but if the data inside is valuable, we will
want to save it to a file and load it back at some point.

In [7]:
points = torch.from_numpy(points_np)
torch.save(points, 'ourpoints.t')

# We can pass a file descriptor in lieu of the filename
with open('ourpoints_alternative.t','wb') as f:
  torch.save(points, f)

# Loading our points back is similarly a one-liner
points = torch.load('ourpoints.t')

# or, equivalently
with open('ourpoints.t','rb') as f:
  points = torch.load(f)
print(points)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Serializing to HDF5 with h5py
HDF5 is a portable, widely supported
format for representing serialized multidimensional arrays, organized in a nested key-value dictionary. Python supports HDF5 through the h5py library (www.h5py.org),
which accepts and returns data in the form of NumPy arrays.

We can install h5py using


```
$ conda install h5py
```

In [8]:
import h5py

# At this point, we can save our points tensor by converting it to a NumPy array
#  and passing it to the create_dataset function:
f = h5py.File('ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

# Here 'coords' is a key into the HDF5 file. We can have other keys—even nested ones.
# One of the interesting things in HDF5 is that we can index the dataset while on disk
# and access only the elements we’re interested in. Let’s suppose we want to load just
# the last two points in our dataset:
f = h5py.File('ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

# We can pass the returned object to the torch.from_numpy function to obtain
# a tensor directly. Note that in this case, the data is copied over to the tensor’s storage:
last_points = torch.from_numpy(dset[-2:])
f.close()

# Moving tensors to the GPU
Every PyTorch tensor can be transferred to (one of) the
GPU(s) in order to perform massively parallel, fast computations. All operations that
will be performed on the tensor will be carried out using GPU-specific routines that
come with PyTorch.

In [4]:
#  we can create a tensor on the GPU by specifying the corresponding argument to
#  the constructor:
import torch
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

# We could instead copy a tensor created on the CPU onto the GPU using
# the to method:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_gpu = points.to(device='cuda')
points_gpu = points.to(device='cuda:0') # Assigning a GPU to allocate the tensor

# Any operation performed on the tensor, such as multiplying all elements by a constant,
# is carried out on the GPU
points = 2 * points                                                   # Multiplication performed on the CPU
print(points)
points_gpu = 2 * points.to(device='cuda')   # Multiplication performed on the GPU
print(points_gpu)

# We can also use the shorthand methods cpu and cuda instead of the to method
#  to achieve the same goal:
points_gpu = points.cuda()              # Defaults to GPU index 0
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]])
tensor([[16.,  4.],
        [20., 12.],
        [ 8.,  4.]], device='cuda:0')
